### ISSUE TITLE
How to install manually?

### ISSUE THREAD

**Issue by mi-skam** [wingyplus/zed-powershell#5]
I tried to download the zip, install the archive. Then I tried to extract it and install it as a dev extension. Do I need to build it before installing it?

**Comment by wingyplus** [comment]
Sorry for the late reply, the extension can be installed via `zed: install dev extension` in Zed. After select the directory, the editor will load the extension and compile it to wasm automatically.

<img width="537" alt="Screenshot 2567-10-24 at 15 51 01" src="https://github.com/user-attachments/assets/00620dd5-ad0e-4f59-9bee-8f834bdc916a">

I'm gonna close this issue since it's not related to the extension. 

Thank you for the interesting in this extension.
